spring:
  freemarker:
    checkTemplateLocation: false
  application:
    name: fucker-api
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: true